2025-02-20 18:35:54,542 - ERROR - An error occurred:
Traceback (most recent call last):
  File "/Users/Sinku/Development/AFC_Automation/utils/custom_exceptions.py", line 30, in <module>
    raise SeleniumException("Browser crashed unexpectedly!")
SeleniumException: Browser crashed unexpectedly! | Contact: BI Automation Team - bi@graphxsys.com

2025-02-20 18:47:26,187 - ERROR - An error occurred:
Traceback (most recent call last):
  File "/Users/Sinku/Development/AFC_Automation/utils/exception_usage.py", line 34, in <module>
    raise SeleniumException("Browser crashed unexpectedly!")
SeleniumException: Browser crashed unexpectedly! | Contact: BI Automation Team - bi@graphxsys.com

2025-02-20 18:47:52,312 - ERROR - An error occurred:
Traceback (most recent call last):
  File "/Users/Sinku/Development/AFC_Automation/utils/exception_usage.py", line 34, in <module>
    raise SeleniumException("Browser crashed unexpectedly!")
SeleniumException: Browser crashed unexpectedly! | Contact: BI Automation Team - bi@graphxsys.com

2025-02-20 18:52:06,660 - ERROR - An error occurred:
Traceback (most recent call last):
  File "/Users/Sinku/Development/AFC_Automation/utils/exception_usage.py", line 34, in <module>
    raise SeleniumException("Browser crashed unexpectedly!")
SeleniumException: Browser crashed unexpectedly! | Contact: BI Automation Team - bi@graphxsys.com

2025-02-20 18:54:34,561 - ERROR - An error occurred:
Traceback (most recent call last):
  File "/Users/Sinku/Development/AFC_Automation/utils/exception_usage.py", line 34, in <module>
    raise SeleniumException("Browser crashed unexpectedly!")
SeleniumException: Browser crashed unexpectedly! | Contact: BI Automation Team - bi@graphxsys.com

2025-02-20 19:05:44,446 - ERROR - An error occurred:
Traceback (most recent call last):
  File "/Users/Sinku/Development/AFC_Automation/utils/exception_usage.py", line 29, in <module>
    raise SeleniumException("Browser crashed unexpectedly!")
SeleniumException: Browser crashed unexpectedly! | Contact: BI Automation Team - bi@graphxsys.com

2025-02-20 20:05:29,936 - ERROR - An error occurred:
Traceback (most recent call last):
  File "c:\Users\Prasad Goled\Desktop\Project\AFC_Automation\utils\exception_usage.py", line 29, in <module>
    raise SeleniumException("Browser crashed unexpectedly!")
SeleniumException: Browser crashed unexpectedly! | Contact: BI Automation Team - bi@graphxsys.com
.

