2025-03-04 15:58:57,776 - INFO - Opened portal
2025-03-04 15:59:10,994 - INFO - Logged in
2025-03-04 15:59:11,005 - INFO - Got portal URL
2025-03-04 15:59:16,658 - INFO - Navigate to method called
2025-03-04 15:59:18,230 - INFO - Search and select report method called
2025-03-04 15:59:20,006 - INFO - Date report range method called
2025-03-04 15:59:20,238 - INFO - Run report method called
2025-03-04 16:02:38,396 - INFO - Opened portal
2025-03-04 16:02:55,405 - INFO - Logged in
2025-03-04 16:02:55,416 - INFO - Got portal URL
2025-03-04 16:03:02,348 - INFO - Navigate to method called
2025-03-04 16:03:04,261 - INFO - Search and select report method called
2025-03-04 16:03:06,209 - INFO - Date report range method called
2025-03-04 16:03:06,568 - INFO - Run report method called
2025-03-04 16:06:17,264 - INFO - Opened portal
2025-03-04 16:06:22,839 - INFO - Logged in
2025-03-04 16:06:22,852 - INFO - Got portal URL
2025-03-04 16:06:28,512 - INFO - Navigate to method called
2025-03-04 16:06:30,890 - INFO - Search and select report method called
2025-03-04 16:06:32,449 - INFO - Date report range method called
2025-03-04 16:06:34,946 - INFO - Run report method called
2025-03-04 16:09:12,213 - INFO - Opened portal
2025-03-04 16:09:23,282 - INFO - Logged in
2025-03-04 16:09:23,299 - INFO - Got portal URL
2025-03-04 16:09:28,296 - INFO - Navigate to method called
2025-03-04 16:09:30,298 - INFO - Search and select report method called
2025-03-04 16:09:31,768 - INFO - Date report range method called
2025-03-04 16:09:34,214 - INFO - Run report method called
2025-03-04 16:09:42,419 - INFO - Download report method called
2025-03-04 16:16:02,107 - INFO - Opened portal
2025-03-04 16:16:07,383 - INFO - Logged in
2025-03-04 16:16:07,404 - INFO - Got portal URL
2025-03-04 16:16:12,483 - INFO - Navigate to method called
2025-03-04 16:16:14,275 - INFO - Search and select report method called
2025-03-04 16:16:15,734 - INFO - Date report range method called
2025-03-04 16:16:18,176 - INFO - Run report method called
2025-03-04 16:16:36,242 - INFO - Download report method called
2025-03-04 16:16:56,903 - INFO - Opened portal
2025-03-04 16:17:02,210 - INFO - Logged in
2025-03-04 16:17:02,225 - INFO - Got portal URL
2025-03-04 16:17:07,274 - INFO - Navigate to method called
2025-03-04 16:17:09,156 - INFO - Search and select report method called
2025-03-04 16:17:10,617 - INFO - Date report range method called
2025-03-04 16:17:12,888 - INFO - Run report method called
2025-03-04 16:17:21,235 - INFO - Download report method called
2025-03-04 16:21:36,884 - INFO - Opened portal
2025-03-04 16:21:41,984 - INFO - Logged in
2025-03-04 16:21:41,994 - INFO - Got portal URL
2025-03-04 16:21:47,193 - INFO - Navigate to method called
2025-03-04 16:21:49,007 - INFO - Search and select report method called
2025-03-04 16:21:51,493 - INFO - Date report range method called
2025-03-04 16:21:54,014 - INFO - Run report method called
2025-03-04 16:22:04,275 - INFO - Download report method called
2025-03-04 16:22:28,317 - INFO - Opened portal
2025-03-04 16:22:33,851 - INFO - Logged in
2025-03-04 16:22:33,866 - INFO - Got portal URL
2025-03-04 16:22:38,543 - INFO - Navigate to method called
2025-03-04 16:22:40,411 - INFO - Search and select report method called
2025-03-04 16:22:41,898 - INFO - Date report range method called
2025-03-04 16:22:44,405 - INFO - Run report method called
2025-03-04 16:22:53,260 - INFO - Download report method called
2025-03-04 16:27:27,941 - INFO - Opened portal
2025-03-04 16:27:36,736 - INFO - Logged in
2025-03-04 16:27:36,749 - INFO - Got portal URL
2025-03-04 16:27:42,432 - INFO - Navigate to method called
2025-03-04 16:27:44,370 - INFO - Search and select report method called
2025-03-04 16:27:46,313 - INFO - Date report range method called
2025-03-04 16:27:48,655 - INFO - Run report method called
2025-03-04 16:27:53,441 - ERROR - Download directory does not exist: C:\Users\Niladri Mallik\Desktop\AFC_Automation\Report Downloads
2025-03-04 16:27:53,441 - INFO - 
2025-03-04 16:31:51,095 - INFO - Opened portal
2025-03-04 16:31:56,812 - INFO - Logged in
2025-03-04 16:31:56,819 - INFO - Got portal URL
2025-03-04 16:32:02,010 - INFO - Navigate to method called
2025-03-04 16:32:04,340 - INFO - Search and select report method called
2025-03-04 16:32:05,842 - INFO - Date report range method called
2025-03-04 16:32:08,548 - INFO - Run report method called
2025-03-04 16:32:16,709 - ERROR - Download directory does not exist: C:\Users\Niladri Mallik\Desktop\AFC_Automation\Report Downloads
2025-03-04 16:32:16,709 - INFO - 
2025-03-04 16:35:14,608 - INFO - Opened portal
2025-03-04 16:35:21,301 - INFO - Logged in
2025-03-04 16:35:21,314 - INFO - Got portal URL
2025-03-04 16:35:28,485 - INFO - Navigate to method called
2025-03-04 16:35:30,314 - INFO - Search and select report method called
2025-03-04 16:35:31,820 - INFO - Date report range method called
2025-03-04 16:35:34,290 - INFO - Run report method called
2025-03-04 16:35:45,004 - INFO - Download report method called
2025-03-04 17:18:27,654 - INFO - Opened portal
2025-03-04 17:18:41,889 - INFO - Logged in
2025-03-04 17:18:41,904 - INFO - Got portal URL
2025-03-04 17:18:44,734 - INFO - Error occurred: <class 'utils.exception_usage.SeleniumException'> Code: SEL_3_002 | Message : Error occurred while navigating to 'Reports'. | Contact: BI Automation Team - bi@graphxsys.com
2025-03-04 17:19:37,697 - INFO - Opened portal
2025-03-04 17:20:24,164 - INFO - Opened portal
2025-03-04 17:20:32,504 - INFO - Logged in
2025-03-04 17:20:32,515 - INFO - Got portal URL
2025-03-04 17:20:38,553 - INFO - Navigate to method called
2025-03-04 17:20:39,643 - INFO - Error occurred: SeleniumException Message : Unable to select report after search. | Contact: BI Automation Team - bi@graphxsys.com
2025-03-04 20:32:20,029 - ERROR - An unexpected error occured : 
Traceback (most recent call last):
  File "c:\Users\Prasad Goled\Desktop\Project\AFC_Automation\utils\experity_base.py", line 810, in logout
    logout_button = self.wait.until(EC.element_to_be_clickable((By.ID,'tdMenuBarItemlogout')))
  File "C:\Users\Prasad Goled\Desktop\Project\AFC_Automation\venv\lib\site-packages\selenium\webdriver\support\wait.py", line 137, in until
    value = method(self._driver)
  File "C:\Users\Prasad Goled\Desktop\Project\AFC_Automation\venv\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 631, in _predicate
    target = driver.find_element(*target)  # grab element at locator
  File "C:\Users\Prasad Goled\Desktop\Project\AFC_Automation\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 898, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\Prasad Goled\Desktop\Project\AFC_Automation\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Prasad Goled\Desktop\Project\AFC_Automation\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id: session deleted as the browser has closed the connection
from disconnected: not connected to DevTools
  (Session info: chrome=133.0.6943.142)
Stacktrace:
	GetHandleVerifier [0x00007FF7EDFAC6A5+28789]
	(No symbol) [0x00007FF7EDF15B20]
	(No symbol) [0x00007FF7EDDA8F9A]
	(No symbol) [0x00007FF7EDD94D75]
	(No symbol) [0x00007FF7EDDB9784]
	(No symbol) [0x00007FF7EDE2F0BF]
	(No symbol) [0x00007FF7EDE4F0D2]
	(No symbol) [0x00007FF7EDE27103]
	(No symbol) [0x00007FF7EDDEFFC0]
	(No symbol) [0x00007FF7EDDF1273]
	GetHandleVerifier [0x00007FF7EE2F1AED+3458237]
	GetHandleVerifier [0x00007FF7EE30829C+3550316]
	GetHandleVerifier [0x00007FF7EE2FDB9D+3507565]
	GetHandleVerifier [0x00007FF7EE072C6A+841274]
	(No symbol) [0x00007FF7EDF209EF]
	(No symbol) [0x00007FF7EDF1CB34]
	(No symbol) [0x00007FF7EDF1CCD6]
	(No symbol) [0x00007FF7EDF0C119]
	BaseThreadInitThunk [0x00007FFA1475259D+29]
	RtlUserThreadStart [0x00007FFA15F6AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Prasad Goled\Desktop\Project\AFC_Automation\utils\main_new.py", line 56, in <module>
    experity.logout()
  File "c:\Users\Prasad Goled\Desktop\Project\AFC_Automation\utils\experity_base.py", line 815, in logout
    raise SeleniumException(f"Code: {em.LOGOUT_ISSUE} | Message : Error occurred during logout.")
utils.exception_usage.SeleniumException: Code: EXP_1_002 | Message : Error occurred during logout. | Contact: BI Automation Team - bi@graphxsys.com

2025-03-04 20:38:11,681 - ERROR - An unexpected error occured : 
Traceback (most recent call last):
  File "c:\Users\Prasad Goled\Desktop\Project\AFC_Automation\utils\experity_base.py", line 183, in login
    self.driver.find_element(By.ID, "txtPassword").save_screenshot(f"Screenshots/Password_Expire_{username}_{TIMESTAMP_IDENTIFIER}.png")
AttributeError: 'WebElement' object has no attribute 'save_screenshot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Prasad Goled\Desktop\Project\AFC_Automation\utils\main_new.py", line 32, in <module>
    experity.login(username, password)
  File "c:\Users\Prasad Goled\Desktop\Project\AFC_Automation\utils\experity_base.py", line 192, in login
    raise SeleniumException(f"Code: {em.INVALID_CREDENTIALS} | Message : Error in Logging process")
utils.exception_usage.SeleniumException: Code: EXP_1 | Message : Error in Logging process | Contact: BI Automation Team - bi@graphxsys.com

2025-03-04 21:13:47,225 - ERROR - Invalid user credentials. Please check username and password.
2025-03-04 22:15:32,437 - ERROR - Invalid user credentials. Please check username and password.
2025-03-04 22:15:45,832 - ERROR - An unexpected error occured : 
Traceback (most recent call last):
  File "c:\Users\Prasad Goled\Desktop\Project\AFC_Automation\utils\main_new.py", line 34, in <module>
    experity.select_pm_report('Financials', 'Revenue', 'REV 14')
  File "c:\Users\Prasad Goled\Desktop\Project\AFC_Automation\utils\experity_base.py", line 61, in wrapper
    raise SeleniumException(f"Message : {func.__name__} failed after {retries} retries.")
utils.exception_usage.SeleniumException: Message : select_pm_report failed after 3 retries. | Contact: BI Automation Team - bi@graphxsys.com

2025-03-05 12:16:47,060 - INFO - Opened portal
2025-03-05 12:16:52,767 - INFO - Logged in
2025-03-05 12:16:52,775 - INFO - Got portal URL
2025-03-05 12:16:57,605 - INFO - Navigate to method called
2025-03-05 12:16:59,115 - INFO - Search and select report method called
2025-03-05 12:17:01,367 - INFO - Date report range method called
2025-03-05 12:17:03,216 - INFO - Run report method called
2025-03-05 12:17:11,778 - INFO - Download report method called
2025-03-05 13:45:41,719 - INFO - Opened portal
2025-03-05 13:45:46,796 - INFO - Logged in
2025-03-05 13:45:46,803 - INFO - Got portal URL
2025-03-05 13:45:51,598 - INFO - Navigate to method called
2025-03-05 13:45:53,067 - INFO - Search and select report method called
2025-03-05 13:45:54,307 - INFO - Date report range method called
2025-03-05 13:45:55,563 - INFO - Run report method called
2025-03-05 13:46:01,850 - INFO - Download report method called
2025-03-05 13:48:13,657 - INFO - Opened portal
2025-03-05 13:48:19,668 - INFO - Logged in
2025-03-05 13:48:19,674 - INFO - Got portal URL
2025-03-05 13:48:24,707 - INFO - Navigate to method called
2025-03-05 13:48:26,161 - INFO - Search and select report method called
2025-03-05 13:48:27,380 - INFO - Date report range method called
2025-03-05 13:48:28,764 - INFO - Run report method called
2025-03-05 13:48:40,061 - INFO - Download report method called
2025-03-05 13:48:58,770 - INFO - Opened portal
2025-03-05 13:49:03,754 - INFO - Logged in
2025-03-05 13:49:03,766 - INFO - Got portal URL
2025-03-05 13:49:08,779 - INFO - Navigate to method called
2025-03-05 13:49:10,187 - INFO - Search and select report method called
2025-03-05 13:49:11,433 - INFO - Date report range method called
2025-03-05 13:49:12,743 - INFO - Run report method called
2025-03-05 13:49:21,917 - INFO - Download report method called
2025-03-05 13:49:49,781 - INFO - Opened portal
2025-03-05 13:49:56,242 - INFO - Logged in
2025-03-05 13:49:56,248 - INFO - Got portal URL
2025-03-05 13:50:01,366 - INFO - Navigate to method called
2025-03-05 13:50:02,746 - INFO - Search and select report method called
2025-03-05 13:50:03,976 - INFO - Date report range method called
2025-03-05 13:50:05,326 - INFO - Run report method called
2025-03-05 13:50:25,882 - INFO - Download report method called
2025-03-05 15:13:20,506 - INFO - Opened portal
2025-03-05 15:13:22,724 - ERROR - Error terminating service process.
Traceback (most recent call last):
  File "C:\Users\Niladri Mallik\Desktop\AFC_Automation\afc_v4_venv\lib\site-packages\selenium\webdriver\common\service.py", line 181, in _terminate_process
    self.process.terminate()
  File "C:\Users\Niladri Mallik\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1589, in terminate
    _winapi.TerminateProcess(self._handle, 1)
OSError: [WinError 6] The handle is invalid
2025-03-05 15:59:35,401 - INFO - Opened portal
2025-03-05 15:59:41,572 - INFO - Logged in
2025-03-05 15:59:41,588 - INFO - Got portal URL
2025-03-05 15:59:46,656 - INFO - Navigate to method called
2025-03-05 15:59:48,931 - INFO - Search and select report method called
2025-03-05 15:59:50,454 - INFO - Date report range method called
2025-03-05 15:59:52,720 - INFO - Run report method called
2025-03-05 16:00:08,187 - INFO - Download report method called
2025-03-05 16:05:43,682 - INFO - Opened portal
2025-03-05 16:05:53,278 - INFO - Error occurred: SeleniumException Code: EXP_1 | Message : Error in Logging process | Contact: BI Automation Team - bi@graphxsys.com
2025-03-05 16:05:57,350 - ERROR - Error terminating service process.
Traceback (most recent call last):
  File "C:\Users\Niladri Mallik\Desktop\AFC_Automation\afc_v4_venv\lib\site-packages\selenium\webdriver\common\service.py", line 181, in _terminate_process
    self.process.terminate()
  File "C:\Users\Niladri Mallik\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1589, in terminate
    _winapi.TerminateProcess(self._handle, 1)
OSError: [WinError 6] The handle is invalid
2025-03-05 16:07:15,792 - INFO - Opened portal
2025-03-05 16:07:17,376 - ERROR - Invalid user credentials. Please check username and password.
2025-03-05 16:07:17,526 - INFO - Logged in
2025-03-05 16:07:17,538 - INFO - Got portal URL
2025-03-05 16:07:18,285 - INFO - Navigate to method called
2025-03-05 16:08:00,546 - INFO - Error occurred: SeleniumException Code: SEL_3_002 | Message : Unable to switch to 'NavFrame' frame. | Contact: BI Automation Team - bi@graphxsys.com
2025-03-05 16:08:02,981 - ERROR - Error terminating service process.
Traceback (most recent call last):
  File "C:\Users\Niladri Mallik\Desktop\AFC_Automation\afc_v4_venv\lib\site-packages\selenium\webdriver\common\service.py", line 181, in _terminate_process
    self.process.terminate()
  File "C:\Users\Niladri Mallik\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1589, in terminate
    _winapi.TerminateProcess(self._handle, 1)
OSError: [WinError 6] The handle is invalid
2025-03-05 16:08:15,426 - INFO - Opened portal
2025-03-05 16:08:17,062 - ERROR - Invalid user credentials. Please check username and password.
2025-03-05 16:08:17,218 - INFO - Logged in
2025-03-05 16:08:17,227 - INFO - Got portal URL
2025-03-05 16:08:17,984 - INFO - Navigate to method called
2025-03-05 16:09:58,062 - INFO - Error occurred: SeleniumException Code: SEL_3_002 | Message : Unable to switch to 'NavFrame' frame. | Contact: BI Automation Team - bi@graphxsys.com
2025-03-05 16:10:00,305 - ERROR - Error terminating service process.
Traceback (most recent call last):
  File "C:\Users\Niladri Mallik\Desktop\AFC_Automation\afc_v4_venv\lib\site-packages\selenium\webdriver\common\service.py", line 181, in _terminate_process
    self.process.terminate()
  File "C:\Users\Niladri Mallik\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1589, in terminate
    _winapi.TerminateProcess(self._handle, 1)
OSError: [WinError 6] The handle is invalid
2025-03-05 16:10:21,435 - INFO - Opened portal
2025-03-05 16:10:23,055 - ERROR - Invalid user credentials. Please check username and password.
2025-03-05 16:10:23,211 - INFO - Logged in
2025-03-05 16:10:23,224 - INFO - Got portal URL
2025-03-05 16:10:24,363 - INFO - Navigate to method called
2025-03-05 16:12:04,438 - INFO - Error occurred: SeleniumException Code: SEL_3_002 | Message : Unable to switch to 'NavFrame' frame. | Contact: BI Automation Team - bi@graphxsys.com
2025-03-05 16:12:06,663 - ERROR - Error terminating service process.
Traceback (most recent call last):
  File "C:\Users\Niladri Mallik\Desktop\AFC_Automation\afc_v4_venv\lib\site-packages\selenium\webdriver\common\service.py", line 181, in _terminate_process
    self.process.terminate()
  File "C:\Users\Niladri Mallik\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1589, in terminate
    _winapi.TerminateProcess(self._handle, 1)
OSError: [WinError 6] The handle is invalid
2025-03-05 16:15:14,528 - INFO - Opened portal
2025-03-05 16:15:15,898 - ERROR - Invalid user credentials. Please check username and password.
2025-03-05 16:15:16,022 - INFO - Error occurred: SeleniumException Code: EXP_1 | Message : Error in Logging process | Contact: BI Automation Team - bi@graphxsys.com
2025-03-05 16:15:18,285 - ERROR - Error terminating service process.
Traceback (most recent call last):
  File "C:\Users\Niladri Mallik\Desktop\AFC_Automation\afc_v4_venv\lib\site-packages\selenium\webdriver\common\service.py", line 181, in _terminate_process
    self.process.terminate()
  File "C:\Users\Niladri Mallik\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1589, in terminate
    _winapi.TerminateProcess(self._handle, 1)
OSError: [WinError 6] The handle is invalid
2025-03-05 16:17:02,762 - INFO - Opened portal
2025-03-05 16:17:04,214 - ERROR - Invalid user credentials. Please check username and password.
2025-03-05 16:17:04,370 - INFO - Error occurred: SeleniumException Code: EXP_1 | Message : Error in Logging process | Contact: BI Automation Team - bi@graphxsys.com
2025-03-05 16:17:06,594 - ERROR - Error terminating service process.
Traceback (most recent call last):
  File "C:\Users\Niladri Mallik\Desktop\AFC_Automation\afc_v4_venv\lib\site-packages\selenium\webdriver\common\service.py", line 181, in _terminate_process
    self.process.terminate()
  File "C:\Users\Niladri Mallik\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1589, in terminate
    _winapi.TerminateProcess(self._handle, 1)
OSError: [WinError 6] The handle is invalid
2025-03-05 16:23:15,937 - ERROR - Invalid user credentials. Please check username and password.
2025-03-05 16:23:18,341 - ERROR - Error terminating service process.
Traceback (most recent call last):
  File "C:\Users\Niladri Mallik\Desktop\AFC_Automation\afc_v4_venv\lib\site-packages\selenium\webdriver\common\service.py", line 181, in _terminate_process
    self.process.terminate()
  File "C:\Users\Niladri Mallik\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1589, in terminate
    _winapi.TerminateProcess(self._handle, 1)
OSError: [WinError 6] The handle is invalid
2025-03-05 20:26:18,233 - ERROR - Invalid user credentials. Please check username and password.
2025-03-05 20:27:05,176 - ERROR - Invalid user credentials. Please check username and password.
2025-03-05 20:27:10,455 - ERROR - Invalid user credentials. Please check username and password.
2025-03-05 20:27:16,227 - ERROR - Invalid user credentials. Please check username and password.
2025-03-05 20:27:21,708 - ERROR - Invalid user credentials. Please check username and password.
2025-03-05 20:27:27,357 - ERROR - Invalid user credentials. Please check username and password.
2025-03-06 11:44:00,359 - INFO - Opened portal
2025-03-06 11:44:06,088 - INFO - Logged in
2025-03-06 11:44:06,101 - INFO - Got portal URL
2025-03-06 11:44:11,196 - INFO - Navigate to method called
2025-03-06 11:44:13,624 - INFO - Search and select report method called
2025-03-06 11:44:16,723 - INFO - Date report range method called
2025-03-06 11:44:19,106 - INFO - Run report method called
2025-03-06 11:49:32,412 - ERROR - Download did not start within the timeout period.
2025-03-06 11:49:32,412 - ERROR - TimeoutError: Download did not start within the allowed time.
2025-03-06 11:49:32,412 - INFO - Error occurred: TimeoutError Download did not start within the allowed time.
2025-03-06 11:49:37,631 - INFO - Opened portal
2025-03-06 11:49:43,291 - INFO - Logged in
2025-03-06 11:49:43,306 - INFO - Got portal URL
2025-03-06 11:49:48,405 - INFO - Navigate to method called
2025-03-06 11:49:50,894 - INFO - Search and select report method called
2025-03-06 11:49:52,333 - INFO - Date report range method called
2025-03-06 11:49:55,349 - INFO - Run report method called
2025-03-06 11:57:30,137 - INFO - Running %s report.
2025-03-06 11:57:30,139 - INFO - Download path already exists.
2025-03-06 11:57:36,202 - INFO - Opened portal
2025-03-06 11:57:41,760 - INFO - Logged in
2025-03-06 11:57:41,774 - INFO - Got portal URL
2025-03-06 11:57:50,428 - INFO - Navigate to method called
2025-03-06 11:57:52,209 - INFO - Search and select report method called
2025-03-06 11:57:54,206 - INFO - Date report range method called
2025-03-06 11:57:56,593 - INFO - Run report method called
2025-03-06 12:03:03,535 - ERROR - Download did not start within the timeout period.
2025-03-06 12:03:03,537 - ERROR - TimeoutError: Download did not start within the allowed time.
2025-03-06 12:03:03,537 - INFO - Error occurred: TimeoutError Download did not start within the allowed time.
2025-03-06 12:03:03,537 - INFO - Running %s report.
2025-03-06 12:03:03,539 - INFO - Download path already exists.
2025-03-06 12:03:08,689 - INFO - Opened portal
2025-03-06 12:03:10,813 - INFO - Error occurred: SeleniumException Code: EXP_1 | Message : Error in Logging process | Contact: BI Automation Team - bi@graphxsys.com
2025-03-06 12:03:10,813 - INFO - Running %s report.
2025-03-06 12:03:10,813 - INFO - Download path already exists.
2025-03-06 12:03:20,307 - INFO - Error occurred: SeleniumException Message : open_portal failed after 3 retries. | Contact: BI Automation Team - bi@graphxsys.com
2025-03-06 12:03:20,307 - INFO - Running %s report.
2025-03-06 12:03:20,307 - INFO - Download path already exists.
2025-03-06 12:03:40,093 - INFO - Running %s report.
2025-03-06 12:03:40,093 - INFO - Download path already exists.
2025-03-06 12:03:45,151 - INFO - Opened portal
2025-03-06 12:03:51,088 - INFO - Logged in
2025-03-06 12:03:51,104 - INFO - Got portal URL
2025-03-06 12:03:55,893 - INFO - Navigate to method called
2025-03-06 12:03:57,720 - INFO - Search and select report method called
2025-03-06 12:03:59,203 - INFO - Date report range method called
2025-03-06 12:04:01,770 - INFO - Run report method called
2025-03-06 12:12:08,705 - INFO - Running %s report.
2025-03-06 12:12:08,707 - INFO - Download path already exists.
2025-03-06 12:12:14,412 - INFO - Opened portal
2025-03-06 12:12:23,097 - INFO - Logged in
2025-03-06 12:12:23,106 - INFO - Got portal URL
2025-03-06 12:12:28,448 - INFO - Navigate to method called
2025-03-06 12:12:30,309 - INFO - Search and select report method called
2025-03-06 12:12:31,798 - INFO - Date report range method called
2025-03-06 12:12:34,451 - INFO - Run report method called
2025-03-06 12:26:58,953 - INFO - Running %s report.
2025-03-06 12:26:58,953 - INFO - Download path already exists.
2025-03-06 12:27:08,355 - INFO - Opened portal
2025-03-06 12:27:17,068 - INFO - Logged in
2025-03-06 12:27:17,076 - INFO - Got portal URL
2025-03-06 12:27:22,436 - INFO - Navigate to method called
2025-03-06 12:27:24,254 - INFO - Search and select report method called
2025-03-06 12:27:25,854 - INFO - Date report range method called
2025-03-06 12:27:28,076 - INFO - Run report method called
2025-03-06 12:32:33,298 - ERROR - Download did not start within the timeout period.
2025-03-06 12:32:33,298 - ERROR - TimeoutError: Download did not start within the allowed time.
2025-03-06 12:32:33,298 - INFO - Error occurred: TimeoutError Download did not start within the allowed time.
2025-03-06 12:32:33,298 - INFO - Running %s report.
2025-03-06 12:32:33,301 - INFO - Download path already exists.
2025-03-06 12:32:38,597 - INFO - Opened portal
2025-03-06 12:32:44,023 - INFO - Logged in
2025-03-06 12:32:44,044 - INFO - Got portal URL
2025-03-06 12:32:50,839 - INFO - Navigate to method called
2025-03-06 12:32:52,739 - INFO - Search and select report method called
2025-03-06 12:32:54,176 - INFO - Date report range method called
2025-03-06 12:32:56,570 - INFO - Run report method called
2025-03-06 12:38:08,045 - ERROR - Download did not start within the timeout period.
2025-03-06 12:38:08,045 - ERROR - TimeoutError: Download did not start within the allowed time.
2025-03-06 12:38:08,045 - INFO - Error occurred: TimeoutError Download did not start within the allowed time.
2025-03-06 12:38:08,047 - INFO - Running %s report.
2025-03-06 12:38:08,049 - INFO - Download path already exists.
2025-03-06 12:38:17,148 - INFO - Opened portal
2025-03-06 12:38:24,725 - INFO - Logged in
2025-03-06 12:38:24,725 - INFO - Got portal URL
2025-03-06 12:38:29,569 - INFO - Navigate to method called
2025-03-06 12:38:31,661 - INFO - Search and select report method called
2025-03-06 12:38:34,697 - INFO - Date report range method called
2025-03-06 12:38:37,551 - INFO - Run report method called
2025-03-06 12:39:44,377 - INFO - Running %s report.
2025-03-06 12:39:44,377 - INFO - Download path already exists.
2025-03-06 12:39:49,994 - INFO - Opened portal
2025-03-06 12:39:56,962 - INFO - Logged in
2025-03-06 12:39:56,978 - INFO - Got portal URL
2025-03-06 12:40:02,058 - INFO - Navigate to method called
2025-03-06 12:40:04,113 - INFO - Search and select report method called
2025-03-06 12:40:05,616 - INFO - Date report range method called
2025-03-06 12:40:07,998 - INFO - Run report method called
2025-03-06 12:41:46,199 - INFO - Running %s report.
2025-03-06 12:41:46,199 - INFO - Download path already exists.
2025-03-06 12:41:51,338 - INFO - Opened portal
2025-03-06 12:41:57,155 - INFO - Logged in
2025-03-06 12:41:57,170 - INFO - Got portal URL
2025-03-06 12:42:02,074 - INFO - Navigate to method called
2025-03-06 12:42:03,927 - INFO - Search and select report method called
2025-03-06 12:42:05,371 - INFO - Date report range method called
2025-03-06 12:42:30,371 - INFO - Running CNT 27 report.
2025-03-06 12:42:30,371 - INFO - Download path already exists.
2025-03-06 12:42:35,562 - INFO - Opened portal
2025-03-06 12:42:41,070 - INFO - Logged in
2025-03-06 12:42:41,084 - INFO - Got portal URL
2025-03-06 12:42:46,816 - INFO - Navigate to method called
2025-03-06 12:42:48,707 - INFO - Search and select report method called
2025-03-06 12:42:50,818 - INFO - Date report range method called
2025-03-06 12:42:53,325 - INFO - Run report method called
2025-03-06 12:46:04,374 - INFO - Running CNT 27 report.
2025-03-06 12:46:04,374 - INFO - Download path already exists.
2025-03-06 12:46:12,615 - INFO - Opened portal
2025-03-06 12:46:20,583 - INFO - Logged in
2025-03-06 12:46:20,598 - INFO - Got portal URL
2025-03-06 12:46:27,011 - INFO - Navigate to method called
2025-03-06 12:46:28,923 - INFO - Search and select report method called
2025-03-06 12:46:30,889 - INFO - Date report range method called
2025-03-06 12:46:33,220 - INFO - Run report method called
2025-03-06 12:51:37,554 - ERROR - Download did not start within the timeout period.
2025-03-06 12:51:37,554 - ERROR - TimeoutError: Download did not start within the allowed time.
2025-03-06 12:51:37,554 - INFO - Error occurred: TimeoutError Download did not start within the allowed time.
2025-03-06 12:51:37,554 - INFO - Running FIN 18 report.
2025-03-06 12:51:37,554 - INFO - Download path already exists.
2025-03-06 12:51:42,795 - INFO - Opened portal
2025-03-06 12:51:48,871 - INFO - Logged in
2025-03-06 12:51:48,887 - INFO - Got portal URL
2025-03-06 12:51:54,143 - INFO - Navigate to method called
2025-03-06 12:51:56,554 - INFO - Search and select report method called
2025-03-06 12:51:58,060 - INFO - Date report range method called
2025-03-06 12:53:38,248 - INFO - Error occurred: SeleniumException Code: EXP_2_002 | Message : Error during logbook status selection. | Contact: BI Automation Team - bi@graphxsys.com
2025-03-06 12:53:38,251 - INFO - Running ADJ 11 report.
2025-03-06 12:53:38,251 - INFO - Download path already exists.
2025-03-06 12:53:43,693 - INFO - Opened portal
2025-03-06 12:53:49,564 - INFO - Logged in
2025-03-06 12:53:49,579 - INFO - Got portal URL
2025-03-06 12:53:54,870 - INFO - Navigate to method called
2025-03-06 12:53:57,271 - INFO - Search and select report method called
2025-03-06 12:54:02,418 - INFO - Date report range method called
2025-03-06 12:55:42,432 - INFO - Error occurred: SeleniumException Code: EXP_2_002 | Message : Error during logbook status selection. | Contact: BI Automation Team - bi@graphxsys.com
2025-03-06 12:55:42,432 - INFO - Running PAY 41 report.
2025-03-06 12:55:42,437 - INFO - Download path already exists.
2025-03-06 12:55:47,488 - INFO - Opened portal
2025-03-06 12:55:53,369 - INFO - Logged in
2025-03-06 12:55:53,382 - INFO - Got portal URL
2025-03-06 12:55:58,741 - INFO - Navigate to method called
2025-03-06 12:56:00,938 - INFO - Search and select report method called
2025-03-06 12:56:02,428 - INFO - Date report range method called
2025-03-06 12:57:42,831 - INFO - Error occurred: SeleniumException Code: EXP_2_002 | Message : Error during logbook status selection. | Contact: BI Automation Team - bi@graphxsys.com
2025-03-06 12:57:42,834 - INFO - Running CNT 19 report.
2025-03-06 12:57:42,834 - INFO - Download path already exists.
2025-03-06 12:57:47,706 - INFO - Opened portal
2025-03-06 12:57:54,144 - INFO - Logged in
2025-03-06 12:57:54,159 - INFO - Got portal URL
2025-03-06 12:57:59,438 - INFO - Navigate to method called
2025-03-06 12:58:01,792 - INFO - Search and select report method called
2025-03-06 12:58:03,745 - INFO - Date report range method called
2025-03-06 12:59:44,206 - INFO - Error occurred: SeleniumException Code: EXP_2_002 | Message : Error during logbook status selection. | Contact: BI Automation Team - bi@graphxsys.com
